USE fitness_log;

-- Insert sample exercises
INSERT INTO exercises (exercise_id, exercise_name, muscle_group, equipment_needed) VALUES
(1,'Squat','Legs','Barbell'),
(2,'Dumbbell Curl','Arms','Dumbbells'),
(3,'Bench Press','Chest','Barbell'),
(4,'Deadlift','Back','Barbell'),
(5,'Running','Cardio','None'),
(6,'Yoga Stretch','Full Body','Mat'),
(7,'Jump Rope','Cardio','Rope'),
(8,'Pull-Up','Back','None'),
(9,'Shoulder Press','Shoulders','Dumbbells'),
(10,'Lunges','Legs','None'),
(11,'Plank','Core','Mat'),
(12,'Bicycle Crunch','Core','Mat'),
(13,'Kettlebell Swing','Full Body','Kettlebell'),
(14,'Rowing','Cardio','Rowing Machine'),
(15,'Leg Press','Legs','Machine'),
(16,'Push-Up','Chest','None'),
(17,'Mountain Climber','Full Body','Mat'),
(18,'Russian Twist','Core','Mat'),
(19,'Burpees','Full Body','None'),
(20,'Lat Pulldown','Back','Machine'),
(21,'Chest Fly','Chest','Machine'),
(22,'Tricep Dip','Arms','None'),
(23,'Side Plank','Core','Mat'),
(24,'Box Jump','Legs','Box'),
(25,'Medicine Ball Slam','Full Body','Medicine Ball'),
(26,'Wall Sit','Legs','None'),
(27,'High Knees','Cardio','None'),
(28,'Hip Thrust','Glutes','Barbell'),
(29,'Cable Row','Back','Cable Machine'),
(30,'Leg Curl','Legs','Machine'),
(31,'Incline Bench Press','Chest','Barbell'),
(32,'Face Pull','Shoulders','Cable Machine'),
(33,'Glute Bridge','Glutes','Mat'),
(34,'Treadmill Running','Cardio','Treadmill'),
(35,'Jumping Jacks','Cardio','None'),
(36,'Dumbbell Row','Back','Dumbbells'),
(37,'Battle Ropes','Full Body','Ropes'),
(38,'Sled Push','Full Body','Sled'),
(39,'Side Lunges','Legs','None'),
(40,'Wall Ball','Full Body','Medicine Ball');
